name: CI/CD for Dockerized Flask App

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

  docker-build-and-publish:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/crop_yield_pred:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/crop_yield_pred:cache  # Docker layer caching
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/crop_yield_pred:cache,mode=max  # Push cache

  deploy-to-ec2:
    needs: docker-build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa  # Ensures the private key is readable by the process
          echo "Host *" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile=/dev/null" >> ~/.ssh/config

      - name: Test SSH Connection
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          timeout: '300s'  # Increased timeout for SSH connection
          command_timeout: '120s'  # Increased command timeout
          debug: true  # Enable debugging for more detailed logs
          script: echo "SSH connection successful"

      - name: Install Docker and configure user on EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          timeout: '300s'  # Increased timeout
          command_timeout: '300s'  # Increased command timeout
          debug: true  # Enable debugging
          script: |
            # Update and install Docker if not already installed
            sudo apt update
            sudo apt install -y docker.io
            sudo systemctl enable docker
            sudo systemctl start docker
            
            # Add 'ubuntu' user to docker group to allow Docker command execution without sudo
            sudo usermod -aG docker ubuntu
            newgrp docker  # Refresh group membership for the current session

      - name: SSH into EC2 and deploy Docker container
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          port: 22
          timeout: '300s'  # Increased timeout
          command_timeout: '300s'  # Increased command timeout
          debug: true  # Enable debugging
          script: |
            # Stop any existing Docker containers
            docker stop my-container || true
            docker rm my-container || true

            # Pull the latest image from Docker Hub
            docker pull ${{ secrets.DOCKER_USERNAME }}/crop_yield_pred:latest

            # Run the Docker container on port 5000
            docker run -d --name my-container -p 5000:5000 ${{ secrets.DOCKER_USERNAME }}/crop_yield_pred:latest
